name: kikagada
description: A Flutter based app build to iOS and Android that provides an easy way to users shares their experiencies with public bathrooms and make ranks of them.
publish_to: 'none' 
version: 1.0.0+2

environment:
  sdk: '>=3.1.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^2.15.1
  firebase_auth: ^4.9.0
  firebase_storage: ^11.2.8
  cloud_firestore: ^4.9.2
  google_sign_in: ^6.1.5
  get_it: ^7.6.4
  mocktail: ^1.0.0
  file_picker: ^6.1.1
  flutter_svg: ^2.0.7
  flutter_rating_bar: ^4.0.1
  permission_handler: ^11.0.1
  uuid: ^4.1.0
  shimmer: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  flutter_native_splash: ^2.3.2
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  assets:
    - lib/shared/assets/app/
    - lib/shared/assets/icons/

  fonts:
    - family: Barlow
      fonts:
        - asset: lib/shared/assets/fonts/Barlow-Black.ttf
          weight: 900
        - asset: lib/shared/assets/fonts/Barlow-ExtraBold.ttf
          weight: 800
        - asset: lib/shared/assets/fonts/Barlow-Bold.ttf
          weight: 700
        - asset: lib/shared/assets/fonts/Barlow-SemiBold.ttf
          weight: 600
        - asset: lib/shared/assets/fonts/Barlow-Medium.ttf
          weight: 500
        - asset: lib/shared/assets/fonts/Barlow-Regular.ttf
          weight: 400
        - asset: lib/shared/assets/fonts/Barlow-Light.ttf
          weight: 300
        - asset: lib/shared/assets/fonts/Barlow-Thin.ttf
          weight: 200
