// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAykNxapFyeOXUAlJrn1v-jYAp5qSLRtQM',
    appId: '1:405829735179:android:157ec7821b41a792de480e',
    messagingSenderId: '405829735179',
    projectId: 'kikagada-38625',
    storageBucket: 'kikagada-38625.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDm9xf6K1ZSvmKXypgGXyJlZhDjYdymqfM',
    appId: '1:405829735179:ios:7431bdda9d237c5ade480e',
    messagingSenderId: '405829735179',
    projectId: 'kikagada-38625',
    storageBucket: 'kikagada-38625.appspot.com',
    androidClientId: '405829735179-1p3lvr55sdd8edf5jc0ag4folsbj34pm.apps.googleusercontent.com',
    iosClientId: '405829735179-0vgd8ovinl7anvkpck6mg0808b7tjo15.apps.googleusercontent.com',
    iosBundleId: 'com.example.kikagada',
  );
}
